meta_product_name: "App From The Dead"
meta_title: "App From The Dead - Give dead apps life"
meta_description: "Entrepreneurs: Find your app - Customize it - Scale it / Developers: Give dead apps life - Post your app - Sell Customizations as a Service"
meta_image: "Full_Logo2.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
